name: dbeaver-ce
version: '5.2.5'
summary: Universal Database Tool
description: |
  Free multi-platform database tool for developers, SQL programmers,
  database administrators and analysts. Supports all popular databases
  MySQL, PostgreSQL, MariaDB, SQLite, Oracle, DB2, SQL Server, Sybase,
  MS Access, Teradata, Firebird, Derby, etc.

architectures:
  - build-on: amd64
    run-on: [amd64, i386]

apps:
  dbeaver:
    command: dbeaver
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-9-openjdk-amd64
      PATH: $JAVA_HOME/bin:$PATH
    aliases: [dbeaver]

parts:
  dbeaver-ce:
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-9-jre-headless
    stage-packages:
      - openjdk-9-jre-headless
      - dbeaver-ce
